### ISSUE TITLE
submission checklist

### ISSUE THREAD

**Issue by pelleran** [pelleran/si507_final_project#28]
canvas submission must contain
- [x] submit link to github
  - [x] add collaborators
- [x] Text summarizing (in less than or equal to 3 sentences) what your project is and does, and how you think it went for you.

**github must contain**

- [x] finalproject file (flask app)
- [x] helper /tool file(s)
- [x] template files
- [x] test file
- [x] requirements.txt
- [x] README
- [x] sample database file
- [x] database schema diagram
- [x] screenshot or clear description what app does
